FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY ./BookingLibrary ./BookingLibrary
COPY ./Client.API ./Client.API
RUN dotnet restore ./Client.API/Client.API.csproj
RUN dotnet publish ./Client.API/Client.API.csproj -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "Client.API.dll"]