FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY ./BookingLibrary ./BookingLibrary
COPY ./Token.API ./Token.API
RUN dotnet restore ./Token.API/Token.API.csproj
RUN dotnet publish ./Token.API/Token.API.csproj -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "Token.API.dll"]







